### ISSUE TITLE
Possible to share the trained weights??

### ISSUE THREAD

**Issue by XiSHEN0220** [euwern/proxynca_pp#3]
Hi, 
Thanks for sharing the code!!!
is it possible to also share the trained weights on CUB, CARS and SOP?  

Best

**Comment by euwern** [comment]
Thank you for your interest in our proxynca++ paper. Unfortunately, we have just deleted our model after ECCV, It should not take too long to train our model. If I remember correctly, the training time on (P100) is CUB (2 to 3 hours), Cars (3 to 5 hours), and SOP (about 10 to 12 hours).
