### ISSUE TITLE
Cub and Cars cropped

### ISSUE THREAD

**Issue by elias-ramzi** [euwern/proxynca_pp#8]
Hi !

Did you use the cropped version of Cub200 and Cars196 in your experiments ?

Thanks,
Elias

**Comment by euwern** [comment]
Hey, If I understand you correctly, you ask whether proxynca++ uses bounding box information to extract images from CUB200 and CARS196. The answer is no; we do not.

**Comment by elias-ramzi** [comment]
Ok, thank you !
